### ISSUE TITLE
Generated Swagger UI did not display security basic authentication 

### ISSUE THREAD

**Issue by leonluocheng** [domaindrivendev/Swashbuckle#1086]
I am using swashbuckle.core 5.5.3. The swagger generated UI did not display the basic authentication that I specified in app configuration. 

Example:

c.BasicAuth("basic").Description("Basic HTTP Authentication over TLS");

![image](https://cloud.githubusercontent.com/assets/8879694/26424613/7e2071de-4097-11e7-8e5f-efb877ea24c6.png)

And I did not specify any apikey here, but an api_key shows up there.

**Comment by coderangerdan** [comment]
I had to hide the APIKey and Explore buttons using a custom CSS injection:
```CSS
form#api_selector input#input_apiKey {
    display: none;
}

form#api_selector A#explore {
    display: none;
}

```
